### ISSUE TITLE
Conflict with Canary

### ISSUE THREAD

**Issue by Snarphe** [cech12/WoodenHopper#12]
The issue seems to be with Canary, but I wanted to reference it here in case someone else encounters it.
https://github.com/AbdElAziz333/Canary/issues/46

**Comment by cech12** [comment]
Thanks for your report. When I have time, I will look into that :)

**Comment by cech12** [comment]
Fixed it on my side by removing the "changed" event after setting the item list.

Fixed in:
- [1.19-1.3.2.1](https://github.com/cech12/WoodenHopper/releases/tag/1.19-1.3.2.1) : https://github.com/cech12/WoodenHopper/commit/34bce30c9e63f99c006646d266eda0bd55b971d6
- [1.18.1-1.2.2.1](https://github.com/cech12/WoodenHopper/releases/tag/1.18.1-1.2.2.1) : https://github.com/cech12/WoodenHopper/commit/8ed9445a7469c33382d67b5edbb57ca88a9a388e
